WebApplication1/Controllers/TeamMemberProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Build.Evaluation;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using WebApplication1.EntityModels;
using WebApplication1.Models.DAL;

namespace WebApplication1.Controllers
{
    public class TeamMemberProjectsController : Controller
    {
        private readonly AppDB _context;

        public TeamMemberProjectsController(AppDB context)
        {
            _context = context;
        }

        // GET: TeamMemberProjects
        public async Task<IActionResult> Index()
        {
            var appDB = _context.TeamMembersProject.Include(t => t.Project).Include(t => t.TeamMember);
            return View(await appDB.ToListAsync());
        }

        // GET: TeamMemberProjects/Details/5
        public async Task<IActionResult> Details(int? teamMemberId, int? projectId)
        {
            if (teamMemberId == null || projectId==null)
            {
                return NotFound();
            }

            var teamMemberProject = await _context.TeamMembersProject
                .Include(t => t.Project)
                .Include(t => t.TeamMember)
                .FirstOrDefaultAsync(m => m.TeamMemberId == teamMemberId && m.ProjectId==projectId);
            if (teamMemberProject == null)
            {
                return NotFound();
            }

            return View(teamMemberProject);
        }

        // GET: TeamMemberProjects/Create
        public IActionResult Create()
        {
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Title");
            ViewData["TeamMemberId"] = new SelectList(_context.TeamMembers, "Id", "Name");
            ViewData["TeamMembers"] = new SelectList(_context.TeamMembers, "Id", "Name");
            return View();
        }

        // POST: TeamMemberProjects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TeamMemberId,ProjectId")] TeamMemberProject teamMemberProject)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teamMemberProject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Title", teamMemberProject.ProjectId);
            ViewData["TeamMemberId"] = new SelectList(_context.TeamMembers, "Id", "Name", teamMemberProject.TeamMemberId);
            return View(teamMemberProject);
        }

        // GET: TeamMemberProjects/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int teamMemberId, int projectId)
        {
            var teamMemberProject = await _context.TeamMembersProject
         .FirstOrDefaultAsync(x => x.TeamMemberId == teamMemberId && x.ProjectId == projectId);
            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Title", teamMemberProject.ProjectId);
            ViewData["TeamMemberId"] = new SelectList(_context.TeamMembers, "Id", "Name", teamMemberProject.TeamMemberId);
            return View(teamMemberProject);
        }

        // POST: TeamMemberProjects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int teamMemberId, int projectId, [Bind("TeamMemberId,ProjectId")] TeamMemberProject teamMemberProject)
        {
            if (teamMemberId != teamMemberProject.TeamMemberId || projectId != teamMemberProject.ProjectId)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    var existing = await _context.TeamMembersProject
    .FirstOrDefaultAsync(x => x.TeamMemberId == teamMemberProject.TeamMemberId && x.ProjectId == teamMemberProject.ProjectId);
                    if (existing != null)
                    {
                        _context.TeamMembersProject.Remove(existing);
                    }

                    var updated = new TeamMemberProject
                    {
                        TeamMemberId = teamMemberProject.TeamMemberId,
                        ProjectId = teamMemberProject.ProjectId
                    };

                    //existing.ProjectId= teamMemberProject.ProjectId;
                    //existing.TeamMemberId= teamMemberProject.TeamMemberId;
                    _context.TeamMembersProject.Add(updated);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    var exists = await _context.TeamMembersProject
                        .AnyAsync(x => x.TeamMemberId == teamMemberId && x.ProjectId == projectId);

                    if (!exists)
                        return NotFound();
                    else
                        throw;
                }
            }

            ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Title", teamMemberProject.ProjectId);
            ViewData["TeamMemberId"] = new SelectList(_context.TeamMembers, "Id", "Name", teamMemberProject.TeamMemberId);
            return View(teamMemberProject);
        }

        // GET: TeamMemberProjects/Delete/5
        public async Task<IActionResult> Delete(int teamMemberId, int projectId)
        {
            var teamMemberProject = await _context.TeamMembersProject
       .Include(tmp => tmp.TeamMember)
            .Include(tmp => tmp.Project)
       .FirstOrDefaultAsync(m => m.TeamMemberId == teamMemberId && m.ProjectId == projectId);

            if (teamMemberProject == null)
                return NotFound();

            return View(teamMemberProject);
        }

        // POST: TeamMemberProjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int teamMemberId, int projectId)
        {
            var teamMemberProject = await _context.TeamMembersProject
         .FirstOrDefaultAsync(x => x.TeamMemberId == teamMemberId && x.ProjectId == projectId);

            if (teamMemberProject != null)
            {
                _context.TeamMembersProject.Remove(teamMemberProject);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool TeamMemberProjectExists(int id)
        {
            return _context.TeamMembersProject.Any(e => e.TeamMemberId == id);
        }

        [HttpPost]
        public async Task<IActionResult> submiprojectmembers([FromBody] TeamMemberProjectCreateDto dto)
        {
            if (dto.SelectedTeamMemberIds == null || dto.ProjectId == 0)
                return BadRequest("Invalid data");

            foreach (var memberId in dto.SelectedTeamMemberIds)
            {
                var tmp = new TeamMemberProject
                {
                    TeamMemberId = memberId,
                    ProjectId = dto.ProjectId // or dto.ProjectId if it's Product
                };
                _context.TeamMembersProject.Add(tmp);
            }

            await _context.SaveChangesAsync();

            var appDB = _context.TeamMembersProject.Include(t => t.Project).Include(t => t.TeamMember);
            return View(await appDB.ToListAsync());
        }





    }
}

WebApplication1/Views/TeamMemberProjects/Create.cshtml
@model WebApplication1.EntityModels.TeamMemberProject
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TeamMemberProject</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" id="teamMemberProjectForm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TeamMemberId" class="control-label"></label>
               @*  <select asp-for="TeamMemberId" class ="form-control" asp-items="ViewBag.TeamMemberId"></select> *@
                <select name="selectedTeamMemberIds" id="teamMembers" multiple class="form-control">
                    @foreach (var member in (MultiSelectList)ViewBag.TeamMembers)
                    {
                        <option value="@member.Value">@member.Text</option>
                    }
                </select>


            </div>
            <div class="form-group">
                <label asp-for="ProjectId" class="control-label"></label>
                <select asp-for="ProjectId" id="ProjectId" class="form-control" asp-items="ViewBag.ProjectId"></select>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#teamMembers').select2({
                placeholder: "Select Team Members",
                allowClear: true,
                width: '100%'
            });

            $('#teamMemberProjectForm').submit(function (e) {
                e.preventDefault();
                debugger;
                const formData = {
                    ProjectId: $('#ProjectId').val(),
                    SelectedTeamMemberIds: $('#teamMembers').val()
                };

                $.ajax({
                    url: '@Url.Action("submiprojectmembers", "TeamMemberProjects")',
                    type: 'POST',
                    contentType: 'application/json',
                    data: JSON.stringify(formData),
                    success: function () {
                        alert('Saved successfully!');
                    },
                    error: function () {
                        alert('Error while saving.');
                    }
                });
            });


        });
    </script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/TeamMemberProjects/Delete.cshtml
@model WebApplication1.EntityModels.TeamMemberProject

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TeamMemberProject</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeamMember)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TeamMember.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Project.Title)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TeamMemberId" />
        <input type="hidden" asp-for="ProjectId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication1/Views/TeamMemberProjects/Details.cshtml
@model WebApplication1.EntityModels.TeamMemberProject

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TeamMemberProject</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeamMember)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TeamMember.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Project.Title)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApplication1/Views/TeamMemberProjects/Edit.cshtml
@model WebApplication1.EntityModels.TeamMemberProject

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TeamMemberProject</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            @* <input type="hidden" asp-for="@Model.TeamMemberId" />
            <input type="hidden" asp-for="@Model.ProjectId" /> *@

            <div class="form-group">
                <label asp-for="TeamMemberId" class="control-label"></label>
                <select asp-for="TeamMemberId" class="form-control" asp-items="ViewBag.TeamMemberId"></select>
            </div>

            <div class="form-group">
                <label asp-for="ProjectId" class="control-label"></label>
                <select asp-for="ProjectId" class="form-control" asp-items="ViewBag.ProjectId"></select>
            </div>

            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/Views/TeamMemberProjects/Index.cshtml
@model IEnumerable<WebApplication1.EntityModels.TeamMemberProject>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TeamMember)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Project)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TeamMember.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Project.Title)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new { teamMemberId = item.TeamMemberId, projectId = item.ProjectId }) |
                    @Html.ActionLink("Details", "Details", new { teamMemberId = item.TeamMemberId, projectId = item.ProjectId }) |
                    @Html.ActionLink("Delete", "Delete", new { teamMemberId = item.TeamMemberId, projectId = item.ProjectId })
            </td>
        </tr>
}
    </tbody>
</table>